#!/usr/local/var/rbenv/versions/2.3.1/bin/ruby

# Add the lib directory to the load path
libdir = File.join(File.dirname(__FILE__), 'lib')
$LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)

require 'bundler/setup'
require 'cog'

Cog.bundle('ec2')
